### ISSUE TITLE
Problem: Nixcloud's information in About us page should be on the left.

### ISSUE THREAD

**Issue by dapyh17d4** [fractalide/fractalide-website-styx#191]
**Step to reproduce**
Go to https://fractalide.com/about_us/ using a desktop computer.

**Actual behaviour**
Nixcloud's information is on the right side.
<img width="1440" alt="screen shot 2018-09-22 at 9 07 05 am" src="https://user-images.githubusercontent.com/39090829/45911630-8f8b6480-be48-11e8-863b-3a4c16bbaafc.png">

**Expected behaviour**
Each row starts on the left, so Nixcloud's information should be on the left. 
<img width="1439" alt="screen shot 2018-09-22 at 9 31 27 am" src="https://user-images.githubusercontent.com/39090829/45911777-518f4000-be4a-11e8-8067-7cb58c63d055.png">

cc @sjmackenzie

**Comment by miguelsimoni** [comment]
I'm gonna close this issue.
Please, reopen it if necessary.
Thanks!

**Comment by sjmackenzie** [comment]
@miguelsimoni seems https://fractalide.com/about_us/ the nixcloud logo isn't on the left :-) Maybe you forgot the PR, is there a technical reason for this being closed?

**Comment by miguelsimoni** [comment]
This issue was fixed and included in PR 193.

https://github.com/fractalide/fractalide-website-styx/pull/193

Honestly, I don't know why this issue wasn't closed automatically.

**Comment by sjmackenzie** [comment]
Ah you need to use the keyword `closes #193` in the commit message3

**Comment by sjmackenzie** [comment]
Strange, if i'm on chromium an the laptop nixcloud still appears on the right.
